#!/bin/bash

while true; do clear;
( uptime;
  echo;
  for Dir in $*; do
    echo "$Dir:"
    Metadata=$Dir;
    if echo $Metadata | grep -q '^/eos'; then
        if test \! -d $Dir/metadata; then
            N=$PPID
            while test -d /dev/shm/$USER/metadata/$N; do
                N=$(( $N + 1 ))
            done;
            mkdir -p /dev/shm/$USER/metadata/$N && ln -sd /dev/shm/$USER/metadata/$N $Dir/metadata;
        fi;
        Metadata=$Dir/metadata
    fi;
    ls -1d $Dir/*_Chunk* > $Metadata/all_chunks
    echo -n " collecing info on $(cat $Metadata/all_chunks | wc -l) chunks, please wait ...";
    cmgListChunksToResub -d $Dir > $Metadata/to_resub;
    ~/sh/running_chunks | sed -e "s#\$HOME#$HOME#g" -e 's#$#/#' > $Metadata/all_really_runing
    : > $Metadata/running; : > $Metadata/to_retry_sub;
    for C in $( awk '/^#.*running/{print $3}' $Metadata/to_resub ); do
        if grep -q "${C}$" $Metadata/all_really_runing; then
             echo "${C}" >> $Metadata/running;
        else
             echo "cmgResubChunk -q 8nh ${C}" >> $Metadata/to_retry_sub;
        fi;
    done
    echo -ne "\r                                                                                     \r";
    echo -n "   Running: "; cat $Metadata/running | wc -l
    echo -n "   NotSub:  "; cat $Metadata/to_retry_sub | wc -l
    echo -n "   Failed:  "; cat $Metadata/to_resub | grep -c -v '^#'  
    echo -n "   Total:   "; cat $Metadata/all_chunks |  wc -l
    sed 's/_Chunk[0-9]\+//g' $Metadata/all_chunks | sort | uniq > $Metadata/all_samples
    echo "   ---"
    echo -e "ALL\tRUN\tFAIL\tGOOD\tACTION\tSAMPLE"
    for S in $(cat $Metadata/all_samples); do
        ALL=$(grep -c ${S}_Chunk $Metadata/all_chunks)
        RUN=$(cat $Metadata/running | grep -c ${S}_Chunk)
        FAIL=$(grep -v running $Metadata/to_resub | cat - $Metadata/to_retry_sub | sort | uniq | grep -c ${S}_Chunk)
        GOOD=$(( $ALL - $RUN - $FAIL ))
        (( $GOOD == $ALL )) && STATUS="done" 
        (( $RUN > 0 )) && STATUS="wait" 
        (( $FAIL > 0 )) && STATUS="CHECK"
        echo -e "$ALL\t$RUN\t$FAIL\t$GOOD\t$STATUS\t$(basename $S)"
    done
    echo
  done;
  echo;
  ~/sh/lsfstat; 
  echo; 
  fs listq ~ ~/w
) | tee ~/public_html/batch-status.txt 
echo; echo sleep; sleep 2m || break; 
done

    
