#!/bin/bash
if echo "X$1" | grep -q '^X-[a-zA-Z0-9]'; then 
    CMSBSUB_QUEUE=$(echo "X$1" | sed 's/^X-//');
    CMSBSUB_DOIT=1;
    shift;
fi;
if [[ "$CMSBSUB_QUEUE" == "" ]]; then CMSBSUB_DOIT=0; fi;
if [[ "$CMSBSUB_DOIT" == "1" ]]; then
    if bqueues $CMSBSUB_QUEUE > /dev/null; then
        bsub -q $CMSBSUB_QUEUE ~/sh/cmsRunBatch $PWD $*;
    fi;
else
    echo bsub -q 1nh ~/sh/cmsRunBatch $PWD $*
    echo "To run now, do export CMSBSUB_DOIT=1; export CMSBSUB_QUEUE=1nh;" 1>&2;
fi;
