#!/bin/bash
export CMSSW_PS1_COLOR=31
export PS1='\[\033[01;31m\]${?/0/\[\033[01;${CMSSW_PS1_COLOR}m\]}[${PWD##${CMSSW_RELEASE_BASE}/src}]\$\[\033[00m\] '
export bsrc="${CMSSW_RELEASE_BASE}/src"
cd $bsrc
hostname | grep -q fnal && echo "$PS1" | grep -q -v LPC && export PS1="\[\033[01;31m\]LPC $PS1"
