#!/bin/bash
ANY=0
USER=gpetrucc; 
if [[ "$1" == "-u" ]]; then USER="$2"; shift; shift; fi;
USR=$(echo $USER | head -c 6)
for q in $(bjobs -u $USER 2> /dev/null | awk "/$USR/{print \$4}" | sort | uniq); do
    echo "   Queue $q ";
    bjobs -u $USER -q $q $* | awk '/:/{print $3"\t"$2}' | sort | uniq -c;
    ANY=1;
done;
if [[ "$ANY" == "0" ]]; then ~/sh/bann "Done"; fi;

