#!/bin/bash
while true; do clear; 
 (echo "$(date) on $(hostname) $(uptime)";
  # ~/sh/lsfstat; echo; 
  condor_q; echo;
  fs listq ~ ~/w ;
  echo; . ~/sh/my-eos-quota ) | tee ~/public_html/status.txt ; 
 echo; echo;
 # MiniAOD list
 #test -f refresh-miniAODlist && . refresh-miniAODlist; 
 # Sleep
 echo sleep; sleep 5m || break; 
 klist > /dev/null || break;
done
