#!/bin/bash
while true; do clear; 
 (uptime; ~/sh/lsfstat; echo; fs listq ~ ~/w ~/scratch0  ; echo; : ~/sh/my-eos-quota ) | tee ~/public_html/status.txt ; 
 # MiniAOD list
 test -f refresh-miniAODlist && . refresh-miniAODlist; 
 # Sleep
 echo sleep; sleep 5m || break; 
 klist > /dev/null || break;
done
